config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)/", locale: /#{I18n.available_locales.join("|")}/ do
    root 'pages#index'
    get '/store' => 'pages#store', as: :store  
    get '/contact' => 'pages#contact', as: :contact   

    get 'strip/random' => 'strips#random', as: :random_strip
    get 'strip/archive' => 'strips#index', as: :archive
    get 'strips/archive' => 'strips#index'
    get 'strip/:id' => 'strips#show', as: :strip
    get 'strips/:id' => 'strips#show'
    
    get 'blog' => 'blogposts#index', as: :blog
    get 'blog/:id' => 'blogposts#show', as: :blogpost
   
    get '/rss' => 'pages#feed', as: :feed, defaults: { format: 'rss' }
    get '/feed' => 'pages#feed', defaults: { format: 'rss' }
    get '/feed.rss' => 'pages#feed', defaults: { format: 'rss' }

    devise_for :admins
    get 'admin' => 'admin/pages#index', as: :admin_root
    namespace :admin do
      resources :strips, :blogposts, :file_uploads
    end
  end

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/strip.rb
class Strip < ActiveRecord::Base
  after_create :extract_filename_data, :increment_publish_date
  before_create :get_latest_strip, :publish
  #after_save :reindex

  acts_as_ordered_taggable

  #searchkick
  
  has_attached_file :image,
                    :styles => { :full => "1000x5000>", :thumb => "600x600>" },
                    :url => "/files/strip/:id/:style/:filename",
                    :path => ":rails_root/public/files/strip/:id/:style/:filename",
                    :use_timestamp => false
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def next
    self.class.published.where("publish_date > ?", publish_date).last
  end

  def previous
    self.class.published.where("publish_date < ?", publish_date).first
  end

  def self.latest
    published.first
  end

  def self.earliest
    published.last
  end

  default_scope { order('publish_date desc') }
  scope :published, -> { where(published: true).where('publish_date <= ?', Date.today) }

  private
    def extract_filename_data
      unless @manual
        filename = File.basename(self.image_file_name, File.extname(self.image_file_name))
        filename.slice!(0..5)

        new_tags = filename.scan(/tag_\w+/)
        new_tags.each {|t| t.gsub! "tag_", ", "}
        new_tags.each {|t| t.gsub! "_,", ","}
        self.tag_list = new_tags

        filename.gsub!(/tag_\w+/,"")
        filename.gsub!('__', ', ')
        filename.slice!((filename.index('_ó'))..-1) if filename.index('_ó')    
        filename.gsub!('_', ' ')
   
        self.title = filename

        self.save
      end
    end

    def get_latest_strip
      @latest_strip = Strip.first
    end

    def increment_publish_date
      unless @manual or !@latest_strip
        self.publish_date = @latest_strip.publish_date + 2.days
        self.save
      end
    end

    def publish
      self.published = true
    end
    
    #def reindex
    #  Strip.reindex
    #end
end

app/controllers/admin/strips_controller.rb
class Admin::StripsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_strip, only: [:show, :edit, :update, :destroy]
  layout "admin"

  def index
    @strip = Strip.new
    @strips = Strip.all
  end

  def show
  end

  def new
    @strip = Strip.new(publish_date: Date.today, published: true)
    @manual = true
  end

  def edit
    @manual = true
  end

  def create
    @strip = Strip.new(strip_params)
    respond_to do |format|
      if @strip.save
        format.html { redirect_to admin_strip_path(@strip), notice: 'Strip was successfully created.' }
        format.json { render :json => {:message => "Success"} }
      else
        format.html { render :new }
        format.json { render json: @strip.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @strip.update(strip_params)
        format.html { redirect_to admin_strips_path, notice: 'Strip was successfully updated.' }
        format.json { render :show, status: :ok, location: @strip }
      else
        format.html { render :edit }
        format.json { render :json => {:message => "Success"} }
      end
    end
  end

  def destroy
    @strip.destroy
    respond_to do |format|
      format.html { redirect_to admin_strips_url, notice: 'Strip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_strip
      @strip = Strip.find(params[:id])
    end

    def strip_params
      params[:strip].permit(:image, :title, :publish_date, :published, :tag_list)
    end
end

app/controllers/strips_controller.rb
class StripsController < ApplicationController
  before_action :set_page_id
  before_action :set_strip, only: [:show]
  before_action :set_links, only: [:show]

  def index
    @page_title = "Archive"
    @strips = Strip.published
    @strip_months = @strips.group_by { |s| s.publish_date.beginning_of_month }
    @popular_tags = ActsAsTaggableOn::Tag.most_used(10)

    #if params[:q]
    #  tag_results = Strip.published.tagged_with(params[:q].split(" "), :any => true, :wild => true) 
    #  title_results = Strip.published.search "#{params[:q]}"
    #  @results = tag_results | title_results
    #  @results_months = @results.group_by { |r| r.publish_date.beginning_of_month }
    #end
  end

  def show
    if @strip
      @page_title = @strip.title
      @related_strips = @strip.find_related_tags.published.limit(5)
    end
  end

  def random
    random_strip = Strip.offset(rand(Strip.count)).first
    redirect_to random_strip
  end

  private
    def set_page_id
      @page_id = "archive"
    end
    
    def set_strip
      if params[:id]
        @strip = Strip.published.find(params[:id])
      else
        @strip = Strip.published.first
      end
    end

    def set_links
      if @strip
        @next_strip = @strip.next
        @previous_strip = @strip.previous
        @first_strip = Strip.published.earliest unless @strip == Strip.published.earliest
        @latest_strip = Strip.published.latest unless @strip == Strip.published.latest
      end
    end
end

app/helpers/admin/strips_helper.rb
module Admin::StripsHelper
end

app/helpers/strips_helper.rb
module StripsHelper
end

app/views/strips/_search_form.html.erb
<%= form_tag("/strip/archive", method: :get, enforce_utf8: false) do %>
  <%= text_field_tag :q, params[:q] %>
  <%= image_submit_tag "btn_search.png", name: nil %>
<% end %>

app/views/strips/_strip.html.erb
<% if strip %>
  <section id="comic" class="<%= 'comichome' unless controller.action_name == 'show' %>">
    <div class="section group">
      <div class="col span_3_of_4">
        <h1><%= strip.title %></h1>
      </div>
      <span class="date col span_1_of_4"><%= l strip.publish_date %></span>
    </div>
    <div class="strip section group">
      <% unless controller.action_name == "show" %>
        <%= link_to image_tag(strip.image.url(:full), alt: strip.title), strip %>
      <% else %>
        <%= image_tag(strip.image.url(:full), alt: strip.title) %>
      <% end %>
    </div>
    <div class="section group">
      <div class="social col span_1_of_3">
      </div>
      <div class="tags col span_1_of_3">
        <% if controller.action_name == "show" %>
          <%= t("strips.tags") %>:
          <% if strip.tag_list.size > 0 %>
            <% strip.tag_list.each do |tag| %>
              <%#= link_to tag, archive_path(q: tag) %><%= tag %><%= ", " unless tag == strip.tag_list.last %>
            <% end %>
          <% else %>
            <%= t("messages.none") %>
          <% end %>
        <% end %>
      </div>
      <div class="language col span_1_of_3">
      </div>
    </div>
    <div class="section group">
      <div id="arrows" class="col span_2_of_2">
        <%= link_to "first", @first_strip, class: "arrow_first" if @first_strip %>
        <%= link_to "first", @first_strip, class: "arrow_first disabled" unless @first_strip %>
        <%= link_to "back", @previous_strip, class: "arrow_back" if @previous_strip %>
        <%= link_to "back", @previous_strip, class: "arrow_back disabled" unless @previous_strip %>
        <%= link_to "random", random_strip_path, class: "arrow_random" %>
        <%= link_to "next", @next_strip, class: "arrow_next" if @next_strip %>
        <%= link_to "next", @next_strip, class: "arrow_next disabled" unless @next_strip %>
        <%= link_to "last", @latest_strip, class: "arrow_last" if @latest_strip %>
        <%= link_to "last", @latest_strip, class: "arrow_last disabled" unless @latest_strip %>
      </div>
    </div>
  </section>
<% end %>

app/views/strips/_strip_thumb.html.erb
<%= link_to image_tag(strip.image.url(:thumb), alt: strip.title) + ("<div><span>#{strip.title}</span></div>").html_safe, strip_path(strip), class: "strip_thumb" %>

app/views/strips/index.html.erb
<section id="content">
  <h1 class="section_header section group">
    <span class="col span_2_of_3"><%= t("navigation.archive") %></span>
    <span class="col span_1_of_3 search">
    <%#= render 'search_form' %>
  </span>
  </h1>
  <% if @results %>
    <% if @results.count > 0 %>
      <% @results_months.each do |month, results| %>
        <h2 class="section_header"><%= month.strftime("%B %Y") %></h2>
        <% results.each do |result| %>
          <%= render "strip_thumb", strip: result %>
        <% end %>
      <% end %>
    <% else %>
      <h2 class="section_header"><% t("messages.no_search_results") %></h2>
    <% end %>
  <% else %>
    <% @strip_months.each do |month, strips| %>
      <h2 class="section_header"><%= l month, format: :month_header %></h2>
      <% strips.each do |strip| %>
        <%= render "strip_thumb", strip: strip %>
      <% end %>
    <% end %>
  <% end %>
</section>

app/views/strips/show.html.erb
<%= render 'strip', strip: @strip %>

<h1 class="section_header section group">
  <span class="col span_2_of_3"><%= t("strips.similar_strips") %></span>
  <span class="col span_1_of_3 search">
    <%#= render 'search_form' %>
  </span>
</h1>
<div class="section group">
  <div class="col span_2_of_3">
    <div class="related_strips">
      <% @related_strips.each do |related_strip| %>
        <%= render "strip_thumb", strip: related_strip %>
      <% end %>
    </div>
  </div>
</div>