config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)/", locale: /#{I18n.available_locales.join("|")}/ do
    root 'pages#index'
    get '/store' => 'pages#store', as: :store  
    get '/contact' => 'pages#contact', as: :contact   

    get 'strip/random' => 'strips#random', as: :random_strip
    get 'strip/archive' => 'strips#index', as: :archive
    get 'strips/archive' => 'strips#index'
    get 'strip/:id' => 'strips#show', as: :strip
    get 'strips/:id' => 'strips#show'
    
    get 'blog' => 'blogposts#index', as: :blog
    get 'blog/:id' => 'blogposts#show', as: :blogpost
   
    get '/rss' => 'pages#feed', as: :feed, defaults: { format: 'rss' }
    get '/feed' => 'pages#feed', defaults: { format: 'rss' }
    get '/feed.rss' => 'pages#feed', defaults: { format: 'rss' }

    devise_for :admins
    get 'admin' => 'admin/pages#index', as: :admin_root
    namespace :admin do
      resources :strips, :blogposts, :file_uploads
    end
  end

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/file_upload.rb
class FileUpload < ActiveRecord::Base
  has_attached_file :attachment,
                    :url => "/files/uploads/:id/:filename",
                    :path => ":rails_root/public/files/uploads/:id/:filename",
                    :use_timestamp => false
  validates_attachment_presence :attachment
  do_not_validate_attachment_file_type :attachment

  default_scope { order('id desc') }
end

app/controllers/admin/file_uploads_controller.rb
class Admin::FileUploadsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_file_upload, only: [:show, :edit, :update, :destroy]
  layout "admin"

  def index
    @file_upload = FileUpload.new
    @file_uploads = FileUpload.all
  end

  def show
  end

  def new
    @file_upload = FileUpload.new
  end

  def edit
  end

  def create
    @file_upload = FileUpload.new(file_upload_params)

    respond_to do |format|
      if @file_upload.save
        format.html { redirect_to admin_file_uploads_url, notice: 'Upload was successfully created.' }
        format.json { render :json => {:message => "Success"} }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @file_upload.update(file_upload_params)
        format.html { redirect_to admin_file_uploads_url, notice: 'Upload was successfully updated.' }
        format.json { render :json => {:message => "Success"} }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @file_upload.destroy
    respond_to do |format|
      format.html { redirect_to admin_file_uploads_url, notice: 'Upload was successfully destroyed.' }
    end
  end

  private
    def set_file_upload
      @file_upload = FileUpload.find(params[:id])
    end

    def file_upload_params
      params.require(:file_upload).permit(:attachment)
    end
end

app/views/admin/file_uploads/_file_upload.html.erb
<div class="admin_file_upload">
  <em><%= link_to file.attachment_file_name, file.attachment.url %></em><br>
  <%= root_url[0..-4] + file.attachment.url %><br><br>
  <small><%= number_to_human_size file.attachment_file_size %> - <%= l file.created_at, format: :long %> - <%= link_to "Edit", edit_admin_file_upload_path(file) %> | <%= link_to 'Delete', admin_file_upload_path(file), method: :delete, data: { confirm: 'Delete file: ' + file.attachment_file_name + '?'  } %></small>
</div><br>

app/views/admin/file_uploads/_form.html.erb
<% if controller.action_name == "new" or controller.action_name == "edit" %>
  <%= form_for([:admin, @file_upload], :html => { multipart: true }) do |f| %>
    <div class="field">
      <% if controller.action_name == "new" %>
        <%= f.label :attachment, t("content.attachment") %>
      <% else %>
        <em><%= link_to @file_upload.attachment_file_name, @file_upload.attachment.url %></em><br>
        <%= root_url + @file_upload.attachment.url %><br><br>
        <%= f.label :attachment, t("content.attachment") %>
      <% end %>
      <br>
      <%= f.file_field :attachment %>
    </div>
    <div class="actions">
      <%= f.submit t("content.save") %>
    </div>
  <% end %>
<% else %>
  <%= form_for([:admin, @file_upload], :html => { multipart: true, class: "dropzone" }) do |f| %>
    <div class="fallback">
      <%= f.label :attachment, t("content.attachment") %><br>
      <%= f.file_field :attachment %><br>
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/admin/file_uploads/edit.html.erb
<div id="admin_form_container">
  <h1><%= t("content.update_file") %></h1>

  <%= render 'form' %>

  <%= link_to t("content.cancel"), admin_file_uploads_path, class: "admin_button" %>
</div>

app/views/admin/file_uploads/index.html.erb
<div id="admin_container">
  <h1><%= t("navigation.file_uploads") %></h1>
  <%= render 'form' %><br>
  <p><%= t("messages.or") %></p>
  <h2><%= link_to t("content.manually_upload_file"), new_admin_file_upload_path %></h2>

  <div id="admin_content_list">
    <% @file_uploads.each do |file| %>
      <div>
        <%= render "file_upload", file: file %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/file_uploads/new.html.erb
<div id="admin_form_container">
  <h1><%= t("content.upload_file") %></h1>

  <%= render 'form' %>

  <%= link_to t("content.cancel"), admin_file_uploads_path, class: "admin_button" %>
</div>

app/views/admin/file_uploads/show.html.erb
<%= render "file_upload", file: @file_upload %>