config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)/", locale: /#{I18n.available_locales.join("|")}/ do
    root 'pages#index'
    get '/store' => 'pages#store', as: :store  
    get '/contact' => 'pages#contact', as: :contact   

    get 'strip/random' => 'strips#random', as: :random_strip
    get 'strip/archive' => 'strips#index', as: :archive
    get 'strips/archive' => 'strips#index'
    get 'strip/:id' => 'strips#show', as: :strip
    get 'strips/:id' => 'strips#show'
    
    get 'blog' => 'blogposts#index', as: :blog
    get 'blog/:id' => 'blogposts#show', as: :blogpost
   
    get '/rss' => 'pages#feed', as: :feed, defaults: { format: 'rss' }
    get '/feed' => 'pages#feed', defaults: { format: 'rss' }
    get '/feed.rss' => 'pages#feed', defaults: { format: 'rss' }

    devise_for :admins
    get 'admin' => 'admin/pages#index', as: :admin_root
    namespace :admin do
      resources :strips, :blogposts, :file_uploads
    end
  end

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
  #after_save :reindex  
  
  #searchkick

  default_scope { order('publish_date desc') }
  scope :published, -> { where(published: true).where('publish_date <= ?', Date.today) }

  def to_param
    [id, title.parameterize].join("-")
  end

  def next
    self.class.published.where("publish_date > ?", publish_date).last
  end

  #def reindex
  #  Blogpost.reindex
  #end
end

app/controllers/admin/blogposts_controller.rb
class Admin::BlogpostsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_blogpost, only: [:show, :edit, :update, :destroy]
  layout "admin"

  def index
    @blogposts = Blogpost.all
  end

  def show
  end

  def new
    @blogpost = Blogpost.new(publish_date: Date.today, published: true)
  end

  def edit
  end

  def create
    @blogpost = Blogpost.new(blogpost_params)

    respond_to do |format|
      if @blogpost.save
        format.html { redirect_to admin_blogpost_path(@blogpost), notice: 'Blogpost was successfully created.' }
        format.json { render :show, status: :created, location: @blogpost }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @blogpost.update(blogpost_params)
        format.html { redirect_to admin_blogpost_path(@blogpost), notice: 'Blogpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogpost }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @blogpost.destroy
    respond_to do |format|
      format.html { redirect_to admin_blogposts_url, notice: 'Blogpost was successfully destroyed.' }
    end
  end

  private
    def set_blogpost
      @blogpost = Blogpost.find(params[:id])
    end

    def blogpost_params
      params.require(:blogpost).permit(:title, :body, :publish_date, :published, :tag_list)
    end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  before_action :set_page_id
  before_action :set_blogpost, only: [:show]

  def index
    @page_title = "Blog"
    @blogposts = Blogpost.published
    @blogpost_months = @blogposts.group_by { |b| b.publish_date.beginning_of_month }

    #if params[:q]
    #  @results = Blogpost.published.search "#{params[:q]}"
    #  @results_months = @results.group_by { |r| r.publish_date.beginning_of_month }
    #end
  end

  def show
    @page_title = @blogpost.title
  end

  private
    def set_page_id
      @page_id = "blog"
    end

    def set_blogpost
      if params[:id]
        @blogpost = Blogpost.published.find(params[:id])
      else
        @blogpost = Blogpost.published.first
      end
    end
end

app/helpers/admin/blogposts_helper.rb
module Admin::BlogpostsHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/views/admin/blogposts/_blogpost.html.erb
<% if blogpost %>
  <article class="section group post_wrapper">
    <div class="col span_1_of_3">
      <h2 class="post_title">
        <%= link_to blogpost.title, edit_admin_blogpost_path(blogpost) %>
      </h2>
    </div>
    <div class="col span_2_of_3">
      <div class="post_content">
        <date><%= link_to l(blogpost.publish_date), edit_admin_blogpost_path(blogpost) %></date>
        <% if blogpost.body.size > 500 %>
          <%=raw Nokogiri::HTML::DocumentFragment.parse(blogpost.body.truncate(500) + " " + link_to("(continued)", blogpost)) %>
        <% else %>
          <%=raw Nokogiri::HTML::DocumentFragment.parse(blogpost.body) %>
        <% end %>
      </div>
    </div>
  </article>
<% end %>

app/views/admin/blogposts/_form.html.erb
<%= form_for([:admin, @blogpost]) do |f| %>
  <% if @blogpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blogpost.errors.count, "error") %> prohibited this blogpost from being saved:</h2>

      <ul>
      <% @blogpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, t("content.title") %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body, t("content.body") %><br>
    <%= f.cktext_area :body %>
  </div>
  <div class="field">
    <%= f.label :publish_date, t("content.publish_on") %><br>
    <%= f.text_field :publish_date, class: "datepicker" %>
  </div>
  <div class="field">
    <%= f.label :published, t("content.published") %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit t("content.save") %>
  </div>
<% end %>

app/views/admin/blogposts/edit.html.erb
<div id="admin_form_container">
  <h1><%= t("blog.update_blogpost") %></h1>

  <%= render 'form' %>

  <%= link_to t("content.cancel"), admin_blogposts_path, class: "admin_button" %>
</div>

app/views/admin/blogposts/index.html.erb
<div id="admin_container">
  <h1><%= t("navigation.blogposts") %></h1>
  <h2><%= link_to t("blog.new_blogpost"), new_admin_blogpost_path %></h2>

  <div id="admin_content_list">
    <% @blogposts.each do |blogpost| %>
      <div>
        <%= render "blogpost", blogpost: blogpost %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/blogposts/new.html.erb
<div id="admin_form_container">
  <h1><%= t("blog.create_blogpost") %></h1>

  <%= render 'form' %>

  <%= link_to t("content.cancel"), admin_blogposts_path, class: "admin_button" %>
</div>

app/views/admin/blogposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blogpost.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blogpost.body %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @blogpost.publish_date %>
</p>

<p>
  <strong>Published:</strong>
  <%= @blogpost.published %>
</p>

<%= link_to 'Edit', edit_admin_blogpost_path(@blogpost) %> |
<%= link_to 'Back', admin_blogposts_path %>