config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)/", locale: /#{I18n.available_locales.join("|")}/ do
    root 'pages#index'
    get '/store' => 'pages#store', as: :store  
    get '/contact' => 'pages#contact', as: :contact   

    get 'strip/random' => 'strips#random', as: :random_strip
    get 'strip/archive' => 'strips#index', as: :archive
    get 'strips/archive' => 'strips#index'
    get 'strip/:id' => 'strips#show', as: :strip
    get 'strips/:id' => 'strips#show'
    
    get 'blog' => 'blogposts#index', as: :blog
    get 'blog/:id' => 'blogposts#show', as: :blogpost
   
    get '/rss' => 'pages#feed', as: :feed, defaults: { format: 'rss' }
    get '/feed' => 'pages#feed', defaults: { format: 'rss' }
    get '/feed.rss' => 'pages#feed', defaults: { format: 'rss' }

    devise_for :admins
    get 'admin' => 'admin/pages#index', as: :admin_root
    namespace :admin do
      resources :strips, :blogposts, :file_uploads
    end
  end

  mount Ckeditor::Engine => '/ckeditor'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<!-- HTML5 Boilerplate -->
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

<head>

  <meta charset="utf-8">
  <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Jordi &amp; Oslo | Administration<%= " | " + @page_title if @page_title %></title>

  <meta http-equiv="cleartype" content="on">

  <%= favicon_link_tag "favicon.png" %>

  <!-- Responsive and mobile friendly stuff -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    '480', media: 'only screen and (max-width: 480px)', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body id="page_<%= @page_id %>">
  <div id="admin_bar"><%= t("messages.administration") %></div>
  <header>
    <div id="header_wrapper" class="section group">
      <div class="col span_1_of_4">
        <%= link_to "JordiOslo.com", admin_root_url, id: "logo" %>
      </div>
      <div class="col span_3_of_4">
        <nav id="admin_nav">
          <%= link_to t("navigation.dashboard"), admin_root_url, class: "btn_admin" %>
          <%= link_to t("navigation.strips"), admin_strips_url, class: "btn_strips" %>
          <%= link_to t("navigation.blogposts"), admin_blogposts_url, class: "btn_blogposts" %>
          <%= link_to t("navigation.file_uploads"), admin_file_uploads_url, class: "btn_file_uploads" %>
          <%= link_to t("navigation.live_site"), root_url %>
          <%= link_to t("accounts.log_out"), destroy_admin_session_url, method: :delete %>
        </nav>
      </div>
      
    </div>
  </header>
  <div id="content_wrapper" class="admin">
    <div id="social_lang">
      <div id="social">
      </div>
      <div id="lang">
        <% if I18n.locale == :ca %>
          <%= link_to "Català", {locale: "ca"}, {class: "lang_ca lang_active"} %>
        <% else %>
          <%= link_to "Català", {locale: "ca"}, {class: "lang_ca"} %>
        <% end %>
        <% if I18n.locale == :en %>
          <%= link_to "Català", {locale: "en"}, {class: "lang_en lang_active"} %>
        <% else %>
          <%= link_to "Català", {locale: "en"}, {class: "lang_en"} %>
        <% end %>
      </div>
    </div>

    <%= yield %>

  </div>
  <footer>

  </footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- HTML5 Boilerplate -->
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

<head>
  <meta charset="utf-8">
  <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> -->

  <title>Jordi &amp; Oslo <%= " | " + @page_title if @page_title %></title>
  <meta name="description" content="">
  <meta name="keywords" content="">

  <meta name="author" content="Guillem Ruiz">

  <!-- <meta http-equiv="cleartype" content="on"> -->
  <%= favicon_link_tag "favicon.png" %>

  <!-- Responsive and mobile friendly stuff -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    '480', media: 'only screen and (max-width: 480px)', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= auto_discovery_link_tag :rss, "http://jordioslo.com/rss" %>
  
<% if @strip %>
  <script>
    function leftArrowPressed() {
        <% if @strip.previous %>
        window.location.href = '<%= url_for(@strip.previous) %>';
        <% end %>
    }

    function rightArrowPressed() {
        <% if @strip.next %>
           window.location.href = '<%= url_for(@strip.next) %>';
        <% end %>
    }

    document.onkeydown = function(evt) {
        evt = evt || window.event;
        switch (evt.keyCode) {
            case 37:
                leftArrowPressed();
                break;
            case 39:
                rightArrowPressed();
                break;
    }
    };
  </script>
<% end %>


</head>
<body id="page_<%= @page_id %>">
  <header>
    <div id="header_wrapper" class="section group">
      <div class="col span_1_of_2">
        <%= link_to "JordiOslo.com", root_url, id: "logo" %>
      </div>
      <div class="col span_1_of_2">
        <nav>
          <%= link_to t("navigation.home"), root_url, class: "btn_home" %>
          <%= link_to t("navigation.blog"), blog_url, class: "btn_blog" %>
          <%= link_to t("navigation.archive"), archive_url, class: "btn_archive" %>
          <%= link_to t("navigation.store"), store_url, class: "btn_store" %>
          <%= link_to t("navigation.contact"), contact_url, class: "btn_contact" %>
        </nav>
      </div>
    </div>
  </header>
  <div id="content_wrapper">
      <div id="lang">
        <% if I18n.locale == :ca %>
          <%= link_to "Català", {locale: "ca"}, {class: "lang_ca lang_active", title: "Català"} %>
        <% else %>
          <%= link_to "Català", {locale: "ca"}, {class: "lang_ca", title: "Català"} %>
        <% end %>
        <% if I18n.locale == :en %>
          <%= link_to "English", {locale: "en"}, {class: "lang_en lang_active", title: "English"} %>
        <% else %>
          <%= link_to "English", {locale: "en"}, {class: "lang_en", title: "English"} %>
        <% end %>
      </div>

    <%= yield %>

  </div>

  <footer>
    &copy; Joveguille 2014 - <%= link_to "RSS", feed_url %>
  </footer>
  
  </body>
</html>